//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rnwa2020.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfStudents", Namespace="http://tempuri.org/", ItemName="students")]
    [System.SerializableAttribute()]
    public class ArrayOfStudents : System.Collections.Generic.List<rnwa2020.ServiceReference1.students> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="students", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class students : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int Faculties_FacultyIdField;
        internal string id;

        public static explicit operator students(rnwa2020.students v)
        {
            throw new NotImplementedException();
        }

        public static explicit operator students(List<students> v)
        {
            throw new NotImplementedException();
        }

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Faculties_FacultyId {
            get {
                return this.Faculties_FacultyIdField;
            }
            set {
                if ((this.Faculties_FacultyIdField.Equals(value) != true)) {
                    this.Faculties_FacultyIdField = value;
                    this.RaisePropertyChanged("Faculties_FacultyId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CourseIdSoap")]
    public interface CourseIdSoap {
        
        // CODEGEN: Generating message contract since element name GetStudentInfoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentInfo", ReplyAction="*")]
        rnwa2020.ServiceReference1.GetStudentInfoResponse GetStudentInfo(rnwa2020.ServiceReference1.GetStudentInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<rnwa2020.ServiceReference1.GetStudentInfoResponse> GetStudentInfoAsync(rnwa2020.ServiceReference1.GetStudentInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentInfo", Namespace="http://tempuri.org/", Order=0)]
        public rnwa2020.ServiceReference1.GetStudentInfoRequestBody Body;
        
        public GetStudentInfoRequest() {
        }
        
        public GetStudentInfoRequest(rnwa2020.ServiceReference1.GetStudentInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetStudentInfoRequestBody() {
        }
        
        public GetStudentInfoRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public rnwa2020.ServiceReference1.GetStudentInfoResponseBody Body;
        
        public GetStudentInfoResponse() {
        }
        
        public GetStudentInfoResponse(rnwa2020.ServiceReference1.GetStudentInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public rnwa2020.ServiceReference1.ArrayOfStudents GetStudentInfoResult;
        
        public GetStudentInfoResponseBody() {
        }
        
        public GetStudentInfoResponseBody(rnwa2020.ServiceReference1.ArrayOfStudents GetStudentInfoResult) {
            this.GetStudentInfoResult = GetStudentInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CourseIdSoapChannel : rnwa2020.ServiceReference1.CourseIdSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseIdSoapClient : System.ServiceModel.ClientBase<rnwa2020.ServiceReference1.CourseIdSoap>, rnwa2020.ServiceReference1.CourseIdSoap {
        
        public CourseIdSoapClient() {
        }
        
        public CourseIdSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseIdSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseIdSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseIdSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        rnwa2020.ServiceReference1.GetStudentInfoResponse rnwa2020.ServiceReference1.CourseIdSoap.GetStudentInfo(rnwa2020.ServiceReference1.GetStudentInfoRequest request) {
            return base.Channel.GetStudentInfo(request);
        }
        
        public rnwa2020.ServiceReference1.ArrayOfStudents GetStudentInfo(int id) {
            rnwa2020.ServiceReference1.GetStudentInfoRequest inValue = new rnwa2020.ServiceReference1.GetStudentInfoRequest();
            inValue.Body = new rnwa2020.ServiceReference1.GetStudentInfoRequestBody();
            inValue.Body.id = id;
            rnwa2020.ServiceReference1.GetStudentInfoResponse retVal = ((rnwa2020.ServiceReference1.CourseIdSoap)(this)).GetStudentInfo(inValue);
            return retVal.Body.GetStudentInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<rnwa2020.ServiceReference1.GetStudentInfoResponse> rnwa2020.ServiceReference1.CourseIdSoap.GetStudentInfoAsync(rnwa2020.ServiceReference1.GetStudentInfoRequest request) {
            return base.Channel.GetStudentInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<rnwa2020.ServiceReference1.GetStudentInfoResponse> GetStudentInfoAsync(int id) {
            rnwa2020.ServiceReference1.GetStudentInfoRequest inValue = new rnwa2020.ServiceReference1.GetStudentInfoRequest();
            inValue.Body = new rnwa2020.ServiceReference1.GetStudentInfoRequestBody();
            inValue.Body.id = id;
            return ((rnwa2020.ServiceReference1.CourseIdSoap)(this)).GetStudentInfoAsync(inValue);
        }
    }
}
